apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: hpa-operator
rules:
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["get","watch","list"]
- apiGroups: ["*"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hpa-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpa-operator
subjects:
- kind: ServiceAccount
  name: hpa-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app: hpa-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hpa-operator
    spec:
      serviceAccountName: hpa-operator
      containers:
      - name: hpa-operator
        image: duym/hpa-operator:v1.14
        command:
          - /bin/hpa-operator
        imagePullPolicy: Always
        volumeMounts:
        - name: template
          mountPath: /template
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: template
        configMap:
          name: hpatemplate