apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app: hpa-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hpa-operator
    spec:
      serviceAccountName: hpa-operator
      containers:
      - name: hpa-operator
        image: duym/hpa-operator:v1.14
        command:
          - /bin/hpa-operator
        imagePullPolicy: Always
        volumeMounts:
        - name: template
          mountPath: /template
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: template
        configMap:
          name: hpatemplate