apiVersion: v1
kind: ConfigMap
metadata:
  name: hpatemplate
data:
  avgCPU50: |-
    type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  avgCPU70: |-
    type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70